name: App

on:
  push:
    branches:
      - pruebas
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        folder: ./frontend
        node-version: 18
    - name: Create container
      run: docker build -t frontend frontend